% Fill in default parameters for the BIRL-GA algorithm.
function algorithm_params = birlgadefaultparams(algorithm_params)

% Create default parameters.
default_params = struct(...
    'seed',          0, ...
    'eta',           1.0, ...
    'normal_prior',  1, ...
    'laplace_prior', 0, ...
    'sigma',         1.0, ...
    'nrestarts',     1, ...
    'all_features',  1, ...
    'true_features', 0);

% Set parameters.
algorithm_params = filldefaultparams(algorithm_params, default_params);
