% Fill in default parameters for the sparse NPB-FIRL algorithm.
function algorithm_params = npbfirldefaultparams(algorithm_params)

% Create default parameters.
default_params = struct(...
    'seed',          0, ...
    'eta',           5.0, ...
    'normal_prior',  1, ...
    'sigma',         1.0, ...
    'alpha',         1.0, ...
    'beta',          1.0, ...
    'a',             1.0, ...
    'b',             4.0, ...
    'lambda',        1.0, ...
    'return_mean',   1, ...
    'max_iters',     200, ...
    'max_pre_iters', 0, ...
    'all_features',  1, ...
    'true_features', 0);

% Set parameters.
algorithm_params = filldefaultparams(algorithm_params, default_params);
